# This flag is used to check if .config/environment.d is actually loaded and
# load it otherwise. One use case is SSH logins which do not inherit the systemd
# environment.
ENVIRONMENT_D_LOADED=1

PATH=${HOME}/.local/bin:${PATH}
