- name: "install dotfiles"
  loop:
    - bash
    - env
    - fish
    - git
    - readline
    - tmux
  ansible.builtin.copy:
    src: "{{ item }}/"
    dest: "{{ ansible_facts['user_dir'] }}/"
    mode: preserve
